/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.QuanLyDatSanDAO39;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhachHang39;
import model.PhieuDatSan39;
import model.SanCon39;

public class TaoPhieuDatSanFrm39 extends javax.swing.JFrame {

    SanCon39 sanCon;
    KhachHang39 khachHang;
    PhieuDatSan39 phieuDatSan;
    DefaultTableModel tmPhieuDatSan;
    
    public TaoPhieuDatSanFrm39(SanCon39 sanCon, KhachHang39 khachHang) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.sanCon = sanCon;
        this.khachHang = khachHang;
        tmPhieuDatSan= (DefaultTableModel)tblPhieuDatSan.getModel();
        eventTaoPhieuDatSan();
    }
    
    private void eventTaoPhieuDatSan(){
       btnXacNhan.addActionListener(e -> {
           try{ 
            if(!txtNgayBatDau.getText().equals("") && !txtNgayKetThuc.getText().equals("")){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");        
                Date ngayBatDau = sdf.parse(txtNgayBatDau.getText());
                Date ngayKetThuc = sdf.parse(txtNgayKetThuc.getText());
                
                LocalDate currentDate = LocalDate.now();
                Date ngayLapPhieu = java.sql.Date.valueOf(currentDate);
                
                int soBuoiTrenTuan = Integer.parseInt(selectSoBuoiTrenTuan.getSelectedItem().toString());
                
                LocalDate localNgayBatDau = ngayBatDau.toInstant().atZone(
                        ZoneId.systemDefault()).toLocalDate();
                LocalDate localNgayKetThuc = ngayKetThuc.toInstant().atZone(
                        ZoneId.systemDefault()).toLocalDate();
                long soTuan = ChronoUnit.WEEKS.between(localNgayBatDau, localNgayKetThuc);
                int tongSoBuoi = (int) (soTuan * soBuoiTrenTuan);
                
                float tienUocTinh = (float) sanCon.getDonGia()*tongSoBuoi;
                float tienDatCoc = tienUocTinh*0.1f;
                phieuDatSan = new PhieuDatSan39(ngayLapPhieu, sanCon.getKhungGioBatDau(), sanCon.getKhungGioKetThuc(), 
                ngayBatDau, ngayKetThuc, soBuoiTrenTuan, sanCon.getDonGia(), tienDatCoc, sanCon, khachHang); 
                
                
                tmPhieuDatSan.setRowCount(0);
                tmPhieuDatSan.addRow(new Object[]{
                    khachHang.getTenKH(), khachHang.getSoDienThoai(), sanCon.getTenSan(), sanCon.getKhungGioBatDau(),
                    sanCon.getKhungGioKetThuc(), txtNgayBatDau.getText(), txtNgayKetThuc.getText(), sanCon.getDonGia(), 
                    tongSoBuoi, tienUocTinh, tienDatCoc
                });
            }else{
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            }
           }catch(ParseException ex){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng!");
           }catch(Exception ex){
                ex.printStackTrace();
           }
       });
       
       btnLuu.addActionListener(e -> {
           try{
               if(phieuDatSan == null){
                   JOptionPane.showMessageDialog(this, "Vui lòng cung cấp đầy đủ thông tin!");
               }else{
                QuanLyDatSanDAO39 dao = new QuanLyDatSanDAO39();
                dao.themPhieuDatSan(phieuDatSan);
                JOptionPane.showMessageDialog(this, "Lưu phiếu đặt sân thành công!");
                this.setVisible(false);
                new TrangChuFrm39().setVisible(true);
               }
           }catch(Exception ex){
                ex.printStackTrace();
           }
       });
       
       btnHuy.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "Hủy đặt sân!");
            this.setVisible(false);
            new TrangChuFrm39().setVisible(true);
       });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNgayBatDau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuDatSan = new javax.swing.JTable();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        selectSoBuoiTrenTuan = new javax.swing.JComboBox<>();
        txtNgayKetThuc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tạo phiếu đặt sân");

        jLabel1.setText("Ngày bắt đầu:");

        jLabel2.setText("Ngày kết thúc:");

        btnXacNhan.setText("Xác nhận");

        tblPhieuDatSan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên khách hàng", "Số điện thoại", "Tên sân", "Giờ bắt đầu", "Giờ kết thúc", "Ngày bắt đầu", "Ngày kết thúc", "Đơn giá", "Tổng số buổi", "Tiền ước tính", "Tiền đặt cọc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPhieuDatSan);

        btnLuu.setText("Lưu");

        btnHuy.setText("Hủy");

        jLabel3.setText("Số buổi trên tuần:");

        selectSoBuoiTrenTuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectSoBuoiTrenTuan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(btnXacNhan)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(btnLuu)
                .addGap(162, 162, 162)
                .addComponent(btnHuy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnXacNhan)
                    .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(selectSoBuoiTrenTuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectSoBuoiTrenTuan;
    private javax.swing.JTable tblPhieuDatSan;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtNgayKetThuc;
    // End of variables declaration//GEN-END:variables
}
