/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.QuanLyDatSanDAO39;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SanCon39;

public class TimSanTrongFrm39 extends javax.swing.JFrame {

    List<SanCon39> listSanCon;
    DefaultTableModel tmSanTrong;
    
    public TimSanTrongFrm39() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        listSanCon = new ArrayList<>();
        tmSanTrong= (DefaultTableModel)tblSanTrong.getModel();
        eventTimKiem();
    }
    
    private void displaySanCon(){  
        int i = 1; 
        for (SanCon39 s : listSanCon) {
            tmSanTrong.addRow(new Object[]{
                i, s.getMaSan(), s.getTenSan(), s.getLoaiSan(), s.getKhungGioBatDau(), 
                s.getKhungGioKetThuc(), s.getDonGia()
            });
            i++; 
        }
    }
    
    private void eventTimKiem(){
        btnTimKiem.addActionListener(e -> {
            try{
                if(!txtKhungGioBatDau.getText().equals("") && !txtKhungGioKetThuc.getText().equals("")){
                    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                    java.util.Date utilDate1 = sdf.parse(txtKhungGioBatDau.getText());
                    java.sql.Date khungGioBatDau = new java.sql.Date(utilDate1.getTime());
                    java.util.Date utilDate2 = sdf.parse(txtKhungGioKetThuc.getText());
                    java.sql.Date khungGioKetThuc = new java.sql.Date(utilDate2.getTime());
                    String loaiSan = selectLoaiSan.getSelectedItem().toString();
                    QuanLyDatSanDAO39 dao = new QuanLyDatSanDAO39();
                    listSanCon = dao.timSanTrong(khungGioBatDau, khungGioKetThuc, loaiSan);
                    if(listSanCon.size()==0){
                        JOptionPane.showMessageDialog(this, "Không có sân trống, vui lòng chọn lại!");
                        txtKhungGioBatDau.setText("");
                        txtKhungGioKetThuc.setText("");
                    }
                    tmSanTrong.setRowCount(0);
                    displaySanCon();
                }else{
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
                }
            }catch(ParseException ex){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng!");                
            }catch(Exception ex){
                ex.printStackTrace();
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectLoaiSan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanTrong = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtKhungGioKetThuc = new javax.swing.JTextField();
        txtKhungGioBatDau = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tìm sân trống");

        jLabel1.setText("Khung giờ bắt đầu:");

        jLabel2.setText("Loại sân:");

        selectLoaiSan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sân cỏ tự nhiên", "Sân cỏ nhân tạo" }));

        tblSanTrong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sân", "Tên sân", "Loại sân", "Khung giờ bắt đầu", "Khung giờ kết thúc", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanTrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanTrongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanTrong);

        btnTimKiem.setText("Tìm kiếm");

        jLabel3.setText("Khung giờ kết thúc:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKhungGioKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtKhungGioBatDau))
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectLoaiSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(btnTimKiem)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(selectLoaiSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(txtKhungGioBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKhungGioKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanTrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanTrongMouseClicked
        // TODO add your handling code here:
        int row = tblSanTrong.getSelectedRow();
        if (row >= 0 && row < tblSanTrong.getRowCount()) {
            SanCon39 sanCon = listSanCon.get(row);
            (new TimKhachHangFrm39(sanCon)).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_tblSanTrongMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectLoaiSan;
    private javax.swing.JTable tblSanTrong;
    private javax.swing.JTextField txtKhungGioBatDau;
    private javax.swing.JTextField txtKhungGioKetThuc;
    // End of variables declaration//GEN-END:variables
}
